### ISSUE TITLE
Tested it but it does not work

### ISSUE THREAD

**Issue by galuel** [cmgchess/view-livechesscloud-pgn#2]
Hi,

I tested https://view-livechesscloud-pgn.vercel.app/download with https://view.livechesscloud.com/#a9b2d7c3-5542-47cd-8938-afdeca739ba5

Using the ID a9b2d7c3-5542-47cd-8938-afdeca739ba5

But it fails, like you can see below :

![Capture d’écran du 2024-07-06 21-40-46](https://github.com/cmgchess/view-livechesscloud-pgn/assets/5245398/ad9d10a6-6384-4a99-9e9d-db1d450f8e33)

Any idea ?

Thank you !

**Comment by cmgchess** [comment]
hi @galuel 
Thanks for reporting the issue!

This seems to break in production only for some reason but locally couldn't replicate. Anyway the issue was with the content-disposition header set from the api. I guess its with the è character  
Couldn't find a proper fix, so i changed it such that the downloaded file name is the same as the tournament id   
Thanks again :)
